INSERT INTO characters(name, age, quote) VALUES ('Shrek', 30, 'Ogres are like onions.');
INSERT INTO characters(name, age, quote) VALUES ('Lord Farquaad', 571, 'Some of you may die, but it''s a sacrifice I am willing to make.'); 
INSERT INTO characters(name, age, quote) VALUES ('Donkey', 20, 'You might have seen a housefly, maybe even a superfly but I bet you ain''t never seen a donkey fly.');
INSERT INTO characters(name, age, quote) VALUES ('Princess Fiona', 27, 'You didn''t slay the dragon?!');
INSERT INTO characters(name, age, quote) VALUES ('Gingerbread Man (Gingy)', 148, 'No, not the buttons. Not my gumdrop buttons.');
INSERT INTO characters(name, age, quote) VALUES ('Blind mouse #1 (Forder)', 119, 'I found some cheese.');
INSERT INTO characters(name, age, quote) VALUES ('Blind mouse #2 (Gorder)', 119, 'Ugh! Awful stuff.');
INSERT INTO characters(name, age, quote) VALUES ('Blind mouse #3 (Horder)', 119, 'This way gents.');
INSERT INTO characters(name, age, quote) VALUES ('Robin Hood', 646, 'I like an honest fight and a saucy little maid');
INSERT INTO characters(name, age, quote) VALUES ('Magic Mirror', 86, 'But don''t let that cool you off. She''s a loaded pistol who likes pina coladas and getting caught in the rain.');
INSERT INTO characters(name, age, quote) VALUES ('Geppetto', 40, 'Now close your eyes and go to sleep.');
INSERT INTO characters(name, age, quote) VALUES ('Thelonious', 40, '#3! Pick #3 my lord!');
INSERT INTO characters(name, age, quote) VALUES ('Duloc Mascot', NULL, 'AHHHHHHHH!');
INSERT INTO characters(name, age, quote) VALUES ('Big Bad Wolf', 90, 'You mean those stories that say I''m a big "bad" wolf?');
INSERT INTO characters(name, age, quote) VALUES ('Dragon', NULL, 'RAWR!');
INSERT INTO characters(name, age, quote) VALUES ('Old Woman', NULL, 'He''s just a little nervous. He''s really quite the chatterbox. Talk, you boneheaded dolt...');
INSERT INTO characters(name, age, quote) VALUES ('Captian of the Gaurds', NULL, 'Get her out of my sight!');
INSERT INTO characters(name, age, quote) VALUES ('Wrestling Fan', NULL, 'The chair! Hit him with the chair!');
INSERT INTO characters(name, age, quote) VALUES ('The Three Little Pigs', 183, 'We ate the cake.');
INSERT INTO characters(name, age, quote) VALUES ('Pinocchio', 140, 'Oh, gosh, no one invited us!');
